CREATE TYPE "AdCategory" AS ENUM ('EPHEMERE', 'ECHANGISME', 'PLURALISME', 'VOYEURISME', 'GROUPE');

ALTER TABLE "profiles" ADD COLUMN "adCategory" "AdCategory";
ALTER TABLE "profiles" ADD COLUMN "useGeolocation" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "profiles" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "profiles" ADD COLUMN "longitude" DOUBLE PRECISION;
ALTER TABLE "profiles" ADD COLUMN "radiusKm" INTEGER NOT NULL DEFAULT 0;
